name: ci

on:
  push:
      paths-ignore:
          - 'doc/**'

jobs:
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: git clone https://github.com/catchorg/Catch2.git
        run: cd Catch2
        run: cmake -Bbuild -H. -DBUILD_TESTING=OFF
        run: sudo cmake --build build/ --target install
      - name: run tests
        run: cd tests && make
